/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.Formatacao;
import apoio.Validacao;
import controladores.ControlaFuncionario;
import entidades.Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import entidades.ComboItem;
import entidades.DAO.CombosDAO;
import entidades.Usuario;

/**
 *
 * @author arthu
 */
public class TelaFuncionario extends javax.swing.JInternalFrame {

    ControlaFuncionario controlaFuncionario = new ControlaFuncionario();
    int codigo = 0;
//    private Usuario usuarioLogado = null;

    /**
     * Creates new form TelaFuncionario1
     */
    public TelaFuncionario() {
        initComponents();
//        usuarioLogado = u;
        montaTabela();
        permissoes();
    }

    private void permissoes() {
        if (!TelaPrincipal.usuarioLogado.getUsuario().equals("admin")) {
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }

    private void montaTabela() {
        ArrayList<Funcionario> funcionarios = controlaFuncionario.recuperarTodos();
        if (funcionarios == null) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar Funcionarios");
        } else {
            tblFuncionario.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {

                        case 1:
                            return "Nome";
                        case 2:
                            return "Cargo";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 3;
                }

                @Override
                public int getRowCount() {
                    return funcionarios.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Funcionario f = funcionarios.get(rowIndex);

                    if (f != null) {
                        switch (columnIndex) {
                            case 0:
                                return f.getIdfuncionario();
                            case 1:
                                return f.getNome();
                            case 2:
                                return f.getCargo();

                        }

                    }

                    return "n/d";
                }
            });

            tblFuncionario.getColumnModel().getColumn(0).setMinWidth(80);
            tblFuncionario.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblFuncionario.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerAbas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);

        lblnome.setText("Nome do Funcionario *");

        lblcargo.setText("Cargo do Funcionario");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnome)
                    .addComponent(lblcargo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblnome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblcargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        containerAbas.addTab("Cadastro", jPanel1);

        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionario);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        containerAbas.addTab("Listagem", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerAbas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerAbas)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        montaTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (Validacao.validarCamposObrigatorios(txtNome, txtCargo)) {
        Funcionario f = new Funcionario();

        String nome = txtNome.getText();
        f.setNome(nome);
        f.setCargo(txtCargo.getText());

        if (codigo == 0) {
            boolean retorno = controlaFuncionario.salvar(f);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                txtNome.setText("");
                txtCargo.setText("");

                txtNome.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            }
        } else {
            f.setIdfuncionario(codigo);
            boolean retorno = controlaFuncionario.editar(f);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
                txtNome.setText("");
                txtCargo.setText("");

                montaTabela();
                containerAbas.setSelectedIndex(1);
                codigo = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            }
        }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        if (tblFuncionario.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, " Selecione alguem caralho");

        } else {

            String idString = String.valueOf(tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 0));
            int idfuncionario = Integer.parseInt(idString);

            Funcionario f = controlaFuncionario.recuperar(idfuncionario);

            if (f == null) {
                JOptionPane.showMessageDialog(null, "Registro não localizado!");
            } else {

                // preenche a variavel codigo que sera usada para salvar ou editar
                codigo = f.getIdfuncionario();

                // mudar a aba ativa para Cadastro
                containerAbas.setSelectedIndex(0);

                // coloca dados nos campos de interface
                txtNome.setText(f.getNome());
                txtCargo.setText(f.getCargo());

                txtNome.requestFocus();
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblFuncionario.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, " Selecione alguem caralho");

        } else {
            String idfuncionarioString = String.valueOf(tblFuncionario.getValueAt(tblFuncionario.getSelectedRow(), 0));
            int idfuncionario = Integer.parseInt(idfuncionarioString);

            boolean retorno = controlaFuncionario.excluir(idfuncionario);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                montaTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JTabbedPane containerAbas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblnome;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
