/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import apoio.Formatacao;
import apoio.Validacao;
import controladores.ControlaProduto;
import entidades.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import entidades.ComboItem;
import entidades.DAO.CombosDAO;

/**
 *
 * @author arthur.silva3
 */
public class TelaProduto extends javax.swing.JInternalFrame {

    ControlaProduto controlaProduto = new ControlaProduto();
    int codigo = 0;

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
        montaTabela();
        Formatacao.formatarDecimal(txtPeso);
        Formatacao.formatarInt(txtQtdestoque);
        permissoes();
    }
   private void permissoes() {
        if (!TelaPrincipal.usuarioLogado.getUsuario().equals("admin")) {
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
        }
    }
    private void montaTabela() {
        ArrayList<Produto> produtos = controlaProduto.recuperarTodos();
        if (produtos == null) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar Produto");
        } else {
            tblProduto.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "ID";
                        case 1:
                            return "Nome";
                        case 2:
                            return "Tipo";
                        case 3:
                            return "Peso";
                        case 4:
                            return "Ingrediente";
                        case 5:
                            return "Quantidade Estoque";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 6;
                }

                @Override
                public int getRowCount() {
                    return produtos.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Produto p = produtos.get(rowIndex);

                    if (p != null) {
                        switch (columnIndex) {
                            case 0:
                                return p.getId();
                            case 1:
                                return p.getNome();
                            case 2:
                                return p.getTipo();
                            case 3:
                                return p.getPeso();
                            case 4:
                                return p.getIngrediente();
                            case 5:
                                return p.getQtdestoque();
                        }

                    }

                    return "n/d";
                }
            });

            tblProduto.getColumnModel().getColumn(0).setMinWidth(80);
            tblProduto.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblProduto.getColumnModel().getColumn(0).setMaxWidth(20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                         


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        containerAbas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblIngrediente = new javax.swing.JLabel();
        txtIngrediente = new javax.swing.JTextField();
        lblQtdesoque = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtPeso = new javax.swing.JFormattedTextField();
        txtQtdestoque = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);

        lblIngrediente.setText("Ingrediente");

        lblQtdesoque.setText("Quantidade estoque");

        lblNome.setText("Nome *");

        lblTipo.setText("TIpo");

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        lblPeso.setText("Peso");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNome)
                    .addComponent(lblTipo)
                    .addComponent(lblPeso)
                    .addComponent(lblIngrediente)
                    .addComponent(txtIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lblQtdesoque)
                    .addComponent(btnSalvar)
                    .addComponent(txtQtdestoque)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPeso, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPeso)
                .addGap(8, 8, 8)
                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIngrediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQtdesoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQtdestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(16, 16, 16))
        );

        containerAbas.addTab("Cadastro", jPanel1);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProduto);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        containerAbas.addTab("Listagem", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(containerAbas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerAbas, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (Validacao.validarCamposObrigatorios(txtNome, txtTipo, txtPeso, txtIngrediente, txtQtdestoque)) {
        Produto p = new Produto();

        String nome = txtNome.getText();
        p.setNome(nome);
        p.setTipo(txtTipo.getText());
        p.setIngrediente(txtIngrediente.getText());

        String qtdestoqueString = txtQtdestoque.getText();
        int qtdestoque = Integer.parseInt(qtdestoqueString);
        p.setQtdestoque(qtdestoque);

        String pesoString = txtPeso.getText();
        double peso = Double.parseDouble(pesoString);
        p.setPeso(peso);

        if (codigo == 0) {
            boolean retorno = controlaProduto.salvar(p);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
                txtNome.setText("");
                txtTipo.setText("");
                txtIngrediente.setText("");
                txtPeso.setText("");
                txtQtdestoque.setText("");

                txtNome.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            }
        } else {
            p.setId(codigo);
            boolean retorno = controlaProduto.editar(p);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
                txtNome.setText("");
                txtTipo.setText("");
                txtIngrediente.setText("");
                txtPeso.setText("");
                txtQtdestoque.setText("");

                montaTabela();
                containerAbas.setSelectedIndex(1);
                codigo = 0;
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");

            }
        }
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        montaTabela();
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblProduto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, " Selecione alguem caralho");

        } else {
            String idString = String.valueOf(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0));
            int idproduto = Integer.parseInt(idString);

            Produto p = controlaProduto.recuperar(idproduto);

            if (p == null) {
                JOptionPane.showMessageDialog(null, "Registro não localizado!");
            } else {

                // preenche a variavel codigo que sera usada para salvar ou editar
                codigo = p.getId();

                // mudar a aba ativa para Cadastro
                containerAbas.setSelectedIndex(0);

                // coloca dados nos campos de interface
                txtNome.setText(p.getNome());
                txtTipo.setText(p.getTipo());
                txtIngrediente.setText(p.getIngrediente());
                txtPeso.setText(String.valueOf(p.getPeso()));
                txtQtdestoque.setText(String.valueOf(p.getQtdestoque()));

                txtNome.requestFocus();
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblProduto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, " Selecione alguem caralho");

        } else {
            String idString = String.valueOf(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0));
            int idproduto = Integer.parseInt(idString);

            boolean retorno = controlaProduto.excluir(idproduto);
            if (retorno) {
                JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
                montaTabela();
            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        montaTabela();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTabbedPane containerAbas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblQtdesoque;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtIngrediente;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtPeso;
    private javax.swing.JFormattedTextField txtQtdestoque;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
